name: dependency_manager
description: All dependency package of project here.
version: 0.0.1

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Google Font
  google_fonts: ^5.0.0

  # Navigation
  go_router: ^8.0.5

  # Service Locator
  get_it: ^7.6.0

  # Storage
  flutter_secure_storage: ^8.0.0

  # Component
  shimmer: ^3.0.0

  # Utils
  equatable: ^2.0.5
  logger: ^1.4.0
  collection: ^1.17.1

  # Firebase
  firebase_core: ^2.14.0
  firebase_analytics: ^10.4.3
  firebase_crashlytics: ^3.3.3
  firebase_remote_config: ^4.2.3

  # Test
  mocktail: ^0.3.0
  bloc_test: ^9.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
